### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by zakiyousufi** [fullstop125/catalog-of-my-things#28]
### Catalog of my things

> _In this project, we create a console app that will help you to keep a record of different types of things we own: books, music albums, movies, and games. Everything is based on the UML class diagram presented below. The data is stored in JSON files but we have also prepared a database with tables structure analogical to our program's class structure._

**_In this milestone @zakiyousufi, and @fullstop125  have added the Kanban board according to these requirements :_** 

- Create an empty repository for your group project.
- Follow the steps described in [curriculum-tools-copy-projects](https://github.com/microverseinc/curriculum-tools-copy-projects) in order to copy the [[TEMPLATE] Ruby Group Capstone Project](https://github.com/microverseinc/curriculum-ruby/projects/1) board.
- Open the GitHub project (Kanban board) in your team repo.
- Open [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md) and read them carefully.
- Open [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) and compare it with the [project requirements](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md).
- Create tasks on your Kanban board based on the [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md).
- Each task should be a separate card that:

> - Has a descriptive title.
> - Has the number of points in the [Xpt] prefix. That number should indicate the number of points that show how complex the task is. 1 point = 1 hour of estimated work. You shouldn't change the points after dividing up cards, even if the actual work takes longer.
> - Has a description of the task.

- Each of the team members should assign themselves to the cards as divided in the [project requirements divided by team member](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things_divided.md) (and time estimate distributions should be fair - no single person should be doing all of the most time-consuming tasks). Decide who will be the assignee for the cards marked as group tasks. All cards on your Kanban board should have assignees.

Find our Kanban board [here](https://github.com/fullstop125/catalog-of-my-things/projects/1)
waiting for your feedback 👍

**Comment by FrederickMih** [comment]
Hi Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights

- The required number of columns has been added to the board :+1: 
- A very good issue summary and title :heavy_check_mark: 
- Each requirement of the project has one corresponding card :+1: 


## Required Changes ♻️

- [x] Based on the requirements of this project, each card on the board has the number of points in the prefix [Xpt]. This number should indicate the number of points that show how complex the task is. 1 point = 1 hour of work. Kindly fix this requirement. This will also determine if the tasks are distributed in a fair manner between the team members. The number of points should be shown as seen in the screenshot below:

![Screenshot from 2022-11-14 16-39-19](https://user-images.githubusercontent.com/63087491/201702030-1358b2f6-d19b-466a-9dfb-e7978d221139.png)

- [x] This project is supposed to be built by three team members but it seems tasks were not assigned to the third team member. Kindly fix :wrench: it.


_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zakiyousufi** [comment]
Hello @FrederickMih 
Thank you so much for your kind review and feedback.
As you mentioned on the second point about number of teammates and assigned persons I should say that our partner didn’t respond today we tried a lot to connect with him but couldn’t
So we start working on project and decided if our partner respond we should give him the `TEAM 3` person task

**Comment by FrederickMih** [comment]
@zakiyousufi, I think you'll require permission from Student Success before you can proceed else wait for the third team member.

Contact Student Success if the third team member doesn't reply.

**Comment by zakiyousufi** [comment]
@FrederickMih We will do thanks for help

**Comment by prolajumokeoni** [comment]
Hi @Team

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
## Highlights
- Good project board setup 🎊 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zakiyousufi** [comment]
@prolajumokeoni 
Thanks for your kind review 😊
